---
abstract: 'Subroutines for FR24-Bot'
author:
  - 'Andrea Telatin <proch@cpan.org>'
build_requires: {}
configure_requires:
  ExtUtils::MakeMaker: '0'
dynamic_config: 0
generated_by: 'Dist::Zilla version 6.012, CPAN::Meta::Converter version 2.150010'
license: mit
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: '1.4'
name: FR24-Bot
provides:
  FR24::Bot:
    file: lib/FR24/Bot.pm
    version: v0.0.1
recommends:
  File::Which: '0'
requires:
  Capture::Tiny: '0.40'
  Carp: '1.2'
  Data::Dumper: '2.1'
  FindBin: '1.3'
  HTTP::Tiny: '0'
  JSON::PP: '0'
  PerlIO::encoding: '0'
  Term::ANSIColor: '5.01'
  WWW::Telegram::BotAPI: '0.12'
  perl: '5.024'
resources:
  repository: https://github.com/telatin/App-Photobear
version: 0.0.1
x_generated_by_perl: v5.30.0
x_serialization_backend: 'YAML::Tiny version 1.73'
